feat: added nip47 feature

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -4,57 +4,49 @@
 FROM python:3.9-bullseye
 
 # Set environment variables
-# Don't write *.pyc files or create __pycache__ dirs
 ENV PYTHONDONTWRITEBYTECODE 1
-
-##### Set environment variables #####
-# Stream python stdout back to calling shell
 ENV PYTHONUNBUFFERED 1
-
-RUN apt update -y
-RUN apt upgrade -y
-RUN apt dist-upgrade -y
-RUN apt autoremove -y
-
-# Prevent tzdata install from requiring user input
 ENV DEBIAN_FRONTEND=noninteractive
 
+RUN apt update -y && apt upgrade -y && apt dist-upgrade -y && apt autoremove -y
+
 # Install additional required tools
-#                        wget git: basic utilities 
-#                            nano: sane text editor
-RUN apt install -y \
-    wget curl git nano
+RUN apt install -y wget curl git nano python3-virtualenv
 
 # Set work directory
 WORKDIR /code
 
-# Set up the interactive bash shell to our liking
+# Copy bashrc
 COPY docker/bashrc /root/.bashrc
 
 # Create virtualenv
-RUN apt install -y python3-virtualenv
 RUN virtualenv -p /usr/bin/python3.9 /srv/.env
 
-#********************** Set up LOCAL server env **********************
-WORKDIR /srv
-RUN git clone https://github.com/kdmukai/nostrtool.git
-
+# Set up the project directory
 WORKDIR /srv/nostrtool
-RUN git clone https://github.com/kdmukai/python-nostr.git
 
+# Copy local repository files
+COPY . .
+
+# Clone python-nostr dependency
+RUN git clone https://github.com/kdmukai/python-nostr.git
 WORKDIR /srv/nostrtool/python-nostr
 RUN git checkout dev
 
+# Install dependencies
 WORKDIR /srv/nostrtool
+RUN sed -i '/Flask==2.2.2/a Werkzeug==2.2.3' requirements.txt
+RUN echo "git+https://github.com/kdmukai/python-nostr.git@dev" >> requirements.txt
 RUN /srv/.env/bin/pip install -r requirements.txt --no-cache-dir
 
-WORKDIR /srv/nostrtool/src
-RUN ln -s ../python-nostr/nostr/ nostr
+# Set work directory
+WORKDIR /srv/nostrtool
 
-# Generate new Flask app secret key
-RUN /srv/.env/bin/python -c 'import secrets; print(secrets.token_hex())' > .app_secret
-
-# Zappa
-# RUN mkdir /root/.aws
-# RUN touch /root/.aws/credentials
-# RUN /srv/.env/bin/pip install zappa --no-cache-dir
+# Remove any existing .app_secret directory and create the secret key file
+RUN rm -rf .app_secret
+RUN echo "Current directory:" && pwd
+RUN /srv/.env/bin/python --version
+RUN /srv/.env/bin/python -c 'import secrets; print(secrets.token_hex())' > .app_secret || { echo "Failed to create .app_secret"; exit 1; }
+RUN ls -la /srv/nostrtool/.app_secret || { echo "File not found"; exit 1; }
+RUN cat /srv/nostrtool/.app_secret
+RUN chmod 644 .app_secret
